<a href="https://colab.research.google.com/github/Zaheer-Aswath/DataScience-Python/blob/main/Edureka/mohammed_zaheer_day8_diy_solution_doc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. Problem Statement: Understanding NumPy Array Functions - I**

Define a NumPy array with 4 * 5 dimensions, and swap the array's dimensions to make it 5 * 4 using suitable functions.

Input Format: You don't need to read any input in this problem.

In [ ]:
import numpy as np
a = np.arange(0,20)
b = a.reshape(4,5)
c = b.T
print("Original Array:\n",a)
print("Reshaped Array:\n",b)
print("Transposed Array:\n",c)

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Transposed Array:
 [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


**Q2. Problem Statement: Understanding NumPy Array Functions - II**

Write a Python program to create two 2-dimensional arrays and apply hstack(), vstack(), concatenate(), and split() functions to them to get the output as shown below.

Input Format: You do not need to read any input in this problem.

In [ ]:
import numpy as np
d = np.array([[1,2],[3,4]])
e = np.array([[6,7],[8,9]])
f = np.hstack((d,e))
g = np.vstack((d,e))
h = np.concatenate((d,e), axis=0)
i = np.split(f,2)
print("First array is:\n",d)
print("Second array is:\n",e)
print("Applying hstack() function:\n",f)
print("Applying vstack() function:\n",g)
print("Applying concatenate() function:\n",h)
print("Applying split() function:\n",i)

First array is:
 [[1 2]
 [3 4]]
Second array is:
 [[6 7]
 [8 9]]
Applying hstack() function:
 [[1 2 6 7]
 [3 4 8 9]]
Applying vstack() function:
 [[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying concatenate() function:
 [[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying split() function:
 [array([[1, 2, 6, 7]]), array([[3, 4, 8, 9]])]
