<a href="https://colab.research.google.com/github/Zaheer-Aswath/DataScience-Python/blob/main/Edureka/mohammed_zaheer_day7_diy_solution_doc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. Problem Statement: Understanding Array Functions**

Write a Python program that takes the speeds of any vehicle to store it in a NumPy array and calculates the average speed.

**Note:** Use NumPy functions to get the desired output.

In [ ]:
import numpy as np
my_list=[]        #creating empty list to add speeds of vehicle
n=int(input("What number of speeds you want to enter?" )) #no.of vehicle speeds
for i in range(0,n): # loop to get as per n number
  speed=int(input("Enter the speeds in Km/hr:"))
  my_list.append(speed) # appending speed in empty list
#print(my_list)  #to verify values entered in list
arr_speed=np.array(my_list) # changing the list values into array
#print(arr_speed) #to verify values changed in array
average_speed=np.mean(arr_speed) #np.mean() used to get the average value from array
print("The Average speed is:",average_speed,"Km/hr")

What number of speeds you want to enter?5
Enter the speeds in Km/hr:92
Enter the speeds in Km/hr:76
Enter the speeds in Km/hr:83
Enter the speeds in Km/hr:78
Enter the speeds in Km/hr:84
The Average speed is: 82.6 Km/hr


**Q2. Problem Statement: Array Indexing/Slicing**

Write a Python program to generate a 3-D array with integers of your choice, perform indexing, and print the first two rows and last two columns of the array.

**Note:** Use NumPy arange() function to generate a random array.

**Input Format:** You do not need to read any input in this problem.

In [ ]:
import numpy as np
arr=np.arange(20).reshape(5,4)
#arr=np.random.randint(0,20,(5,4)) # for random elements in array
print(arr)
first_two_rows = arr[0:2] #here 0 is row(from) and 2 is row excluded i.e row 1
print(first_two_rows)
last_two_columns = arr[0:5,2:4] #here 0:5 is row(from) and 2:4 is column
print(last_two_columns)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]
